/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

typedef volatile unsigned int        vuint32_t;
//register addresses
#define RCC_BASE                     0x40021000
#define GPIOA_BASE                   0x40010800
#define RCC_APB2ENR                  *(volatile uint32_t*)(RCC_BASE + 0x18)
#define GPIOA_CRH                    *(volatile uint32_t*)(GPIOA_BASE + 0x04)
#define GPIOA_ODR                    *(volatile uint32_t*)(GPIOA_BASE + 0x0C)

typedef union {
	vuint32_t all_fields;
	struct{
		vuint32_t  reserved:13; //0 -> 12 reserved
		vuint32_t  Pin_13:1;
	}Pin;
}R_ODR_t;

int main(void)
{
	volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(GPIOA_BASE + 0x0C);

	RCC_APB2ENR |= (1<<2); //enable clock enter to GPIO

	GPIOA_CRH &= 0xFF0FFFFF; //clear the bits from 20 to 24
	GPIOA_CRH |= 0x00200000; //set bits from 20 to 24 by 2

	while(1)
	{
		//GPIOA_ODR |= 1<<13; //set bit 13 by 1 (led on)
		R_ODR->Pin.Pin_13 = 1;
		for(int i = 0 ; i < 5000 ; i++); //delay for 5 msec

		//GPIOA_ODR &= ~(1<<13); //clear bit 13 (led off)
		R_ODR->Pin.Pin_13 = 0;
		for(int i = 0 ; i < 5000 ; i++); //delay for 5 msec
	}

	return 0 ;


}
